version: '2'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    image: postgres:9.5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file: ./compose/postgres/.env.postgres
    restart: always
    network_mode: "bridge"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    env_file:
      - ./compose/postgres/.env.postgres
      - ./compose/django/.env.dev
      - ./compose/django/.env.s3
    volumes:
      - .:/app
    expose:
      - "8000"
    links:
      - postgres
    restart: always
    network_mode: "bridge"
