version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: ./compose/postgres/.env.postgres
    restart: always
    network_mode: "bridge"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: ./compose/django/.env.production
    expose:
      - "5000"
    restart: always
    network_mode: "bridge"

  redis:
    image: redis:latest
    restart: always
    network_mode: "bridge"
{% if cookiecutter.use_celery == 'y' %}
  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: .env
    depends_on:
     - postgres
     - redis
    command: celery -A {{cookiecutter.project_slug}}.taskapp worker -l INFO
    restart: always
    network_mode: "bridge"

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: celery -A {{cookiecutter.project_slug}}.taskapp beat -l INFO
    restart: always
    network_mode: "bridge"
{% endif %}
